# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
$directory\
$fill\
$git_branch\
$git_state\
$git_status\
$time $cmd_duration\
$line_break $character"""

[username]
show_always = true
style_user = "bright-yellow"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bright-green"
format = "[@](bright-black)[$hostname]($style)"

[directory]
style = "white"
truncation_length = 3
truncate_to_repo = false
format = "[: ](bright-black)[$path]($style)"

[character]
success_symbol = "[>](bold bright-black) "
error_symbol = "[>](bold bright-black) "

[fill]
symbol = " "

[git_branch]
format = "[branch $branch(:$remote_branch)]($style) "
style = "bright-blue"

[git_state]
format = '[$state \($progress_current/$progress_total\)]($style) '

[git_status]
style = "green"
untracked = "[$count U](red)[ / ](white)"
modified = "[$count M](yellow)"
staged = "[ / ](white)[$count S](green)"
diverged = '\[!!!\] '
ahead = '\[$count ahead\] '
behind = '\[$count behind\] '
format = '[$ahead_behind](purple)$untracked$modified$staged'

[cmd_duration]
format = '[\($duration\)]($style)'
style = "bright-yellow"

[time]
disabled = false
style = "orange"
utc_time_offset = "0"
format = '[ --](bright-black) [$time UTC]($style)'

